chore: simplify

diff --git a/.github/workflows/audit-dependencies.yml b/.github/workflows/audit-dependencies.yml
--- a/.github/workflows/audit-dependencies.yml
+++ b/.github/workflows/audit-dependencies.yml
@@ -33,15 +33,15 @@ jobs:
         id: audit_dependencies
         run: ./.github/workflows/audit-dependencies.sh ${{ inputs.audit-level }}
 
-      - name: Failure output
-        if: failure()
-        run: |
-          set -ex
-          echo "Vulnerabilities found."
-          cat audit_output.json
-          # echo audit_dependencies.outputs.audit_output
-          echo "${{ steps.audit_dependencies.outputs.audit_output }}"
-          # echo "All outputs: ${{ toJson(steps.audit_dependencies.outputs) }}"
+      # - name: Failure output
+      #   if: failure()
+      #   run: |
+      #     set -ex
+      #     echo "Vulnerabilities found."
+      #     cat audit_output.json
+      #     # echo audit_dependencies.outputs.audit_output
+      #     echo "${{ steps.audit_dependencies.outputs.audit_output }}"
+      #     # echo "All outputs: ${{ toJson(steps.audit_dependencies.outputs) }}"
 
       - name: Slack notification on failure
         if: failure()
@@ -57,15 +57,8 @@ jobs:
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
-                    "text": "Actionable vulnerabilities found: ${{ steps.audit_dependencies.outputs.audit_output }}"
+                    "text": "Actionable vulnerabilities found: \n<${{ github.event.pull_request.html_url || github.event.head_commit.url }}|View Details>"
                   }
                 },
-                {
-                  "type": "section",
-                  "text": {
-                    "type": "mrkdwn",
-                    "text": "GitHub Action build result: ${{ job.status }}\n<${{ github.event.pull_request.html_url || github.event.head_commit.url }}|View Details>"
-                  }
-                }
               ]
             }
